language: java

jdk:
  - oraclejdk8

services:
  - rabbitmq
  - redis-server

sudo: false

cache:
  directories:
  - $HOME/.gradle

env:
  - TERM=dumb

install: true

script:
  - travis_wait ./gradlew --debug clean build distZip -x test -PtestLoggingStarted=true -PwikiBranch=origin/master

#test
