language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle

env:
  - TERM=dumb

install: true

script:
  - ./gradlew clean build install -x test

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "build/distributions/spring-xd-1.3.2.BUILD-SNAPSHOT-dist.zip"
  skip_cleanup: true
  on:
    tags: true
    overwrite: true
