language: java

jdk:
  - oraclejdk8

services:
  - rabbitmq
  - redis-server

sudo: false

cache:
  directories:
  - $HOME/.gradle

env:
  - TERM=dumb

install: true

script:
  - ./gradlew clean build distZip -x test

#test
